export enum drawConstants {
  NO_TOOL = 'NO_TOOL',
  PAINTBRUSH = 'PAINTBRUSH',
  START_DRAW = 'STARTDRAW',
  STOP_DRAW = 'STOP_DRAW',
  SET_COLOR = 'SET_COLOR',
  SHOW_SIZE_BAR = 'SHOW_SIZE_BAR',
  HIDE_SIZE_BAR = 'HIDE_SIZE_BAR',
  SET_SIZE = 'SET_SIZE',
  SHOW_SHAPE_BAR = 'SHOW_SHAPE_BAR',
  HIDE_SHAPE_BAR = 'HIDE_SHAPE_BAR',
}
